rules:
  - id: python-security-best-practices
    patterns:
      - pattern: eval(...)
    message: Avoid use of eval()
    severity: ERROR
    languages: [python]

  - id: flask-debug-enabled
    patterns:
      - pattern: app.run(..., debug=True, ...)
    message: Flask debug mode must not be enabled
    severity: ERROR
    languages: [python]
